[package]
name = "rabbit"
version = "0.1.0"
authors = ["sueken5"]

[dependencies]
inc = { path = "inc" }
hwio = { path = "hwio" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
