version: '3.7'

services:
  rabbit:
    build: ./
    image: sueken5/rabbit
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    working_dir: /rabbit
    volumes:
      - ./:/rabbit:cached
